[json] inline generic objects 889
Xyna-Factory/xyna-factory pull request #898
Opened 2024-06-18 06:11 UTC by LukasFey-GIP

2024-06-18 06:27 UTC, corneliuslippert-gip requested changes
see inline comment

2024-06-18 06:27 UTC, corneliuslippert-gip commented on modules/xfmg/json/XMOM/xfmg/xfctrl/datamodel/json/parameter/JSONWritingOptions.xml
> +      <Documentation>If set to true, xfmg.xfctrl.datamodel.json.JSONObject and xfmg.xfctrl.datamodel.json.JSONValue are written using the generic serialization process. If set to null, xfmg.json.Gene
Add to the documentation (here and in JSONParsingOptions):

1. xfmg.json.GenericProcessing is a XynaProperty
2. Explain what happens for "false"

2024-06-20 09:01 UTC, SimonFranzGIP approved these changes

2024-06-24 06:21 UTC, corneliuslippert-gip approved these changes

2024-06-24 06:23 UTC, merged

2024-06-25 12:52 UTC, LukasFey-GIP commented
Breaking Change management:

* wiki: https://github.com/Xyna-Factory/xyna-factory/wiki/Breaking-Change:-Inline-Generic-Json-Objects
* activation: #914 
* cleanup: #915